
KNOWLEDGE_BASE = {
    "home": "### Home Page (Main Entry Point)\n- **Purpose**: Image upload and global comparison view\n- **Features**:\n  - Upload images (PNG, JPG, JPEG, WEBP formats)\n  - View original vs processed image side-by-side\n  - Reset to original image\n  - Download processed image as PNG\n- **Workflow**: Users must upload an image here first before accessing processing pages",
    "upload": "### Home Page (Main Entry Point)\n- **Purpose**: Image upload and global comparison view\n- **Features**:\n  - Upload images (PNG, JPG, JPEG, WEBP formats)\n  - View original vs processed image side-by-side\n  - Reset to original image\n  - Download processed image as PNG\n- **Workflow**: Users must upload an image here first before accessing processing pages",
    "download": "### Home Page (Main Entry Point)\n- **Purpose**: Image upload and global comparison view\n- **Features**:\n  - Upload images (PNG, JPG, JPEG, WEBP formats)\n  - View original vs processed image side-by-side\n  - Reset to original image\n  - Download processed image as PNG\n- **Workflow**: Users must upload an image here first before accessing processing pages",
    
    "basic": "### Page 1: Basic Operations\n- **Purpose**: Pixel-level transformations\n- **Operations**:\n  1. **Convert to Grayscale**: Converts RGB image to grayscale (displayed as RGB for comparison)\n  2. **Invert Colors (Negative)**: Creates a negative image by inverting all pixel values (255 - pixel)\n- **No parameters required** - simple one-click operations",
    "grayscale": "### Page 1: Basic Operations\n- **Purpose**: Pixel-level transformations\n- **Operations**:\n  1. **Convert to Grayscale**: Converts RGB image to grayscale (displayed as RGB for comparison)\n  2. **Invert Colors (Negative)**: Creates a negative image by inverting all pixel values (255 - pixel)\n- **No parameters required** - simple one-click operations",
    "invert": "### Page 1: Basic Operations\n- **Purpose**: Pixel-level transformations\n- **Operations**:\n  1. **Convert to Grayscale**: Converts RGB image to grayscale (displayed as RGB for comparison)\n  2. **Invert Colors (Negative)**: Creates a negative image by inverting all pixel values (255 - pixel)\n- **No parameters required** - simple one-click operations",
    "negative": "### Page 1: Basic Operations\n- **Purpose**: Pixel-level transformations\n- **Operations**:\n  1. **Convert to Grayscale**: Converts RGB image to grayscale (displayed as RGB for comparison)\n  2. **Invert Colors (Negative)**: Creates a negative image by inverting all pixel values (255 - pixel)\n- **No parameters required** - simple one-click operations",
    
    "filter": "### Page 2: Filtering (Smoothing and Noise Reduction)\n- **Purpose**: Apply blur filters to reduce noise and smooth images\n- **Kernel Size Parameter**: Slider (1-21, odd numbers only, default: 5)\n- **Operations**:\n  1. **Gaussian Blur**: Uses Gaussian distribution for smooth blurring\n  2. **Median Blur**: Effective for salt-and-pepper noise (requires kernel size ≥ 3)\n  3. **Average Blur**: Simple box filter averaging\n- **Note**: Kernel size must be odd for proper operation",
    "blur": "### Page 2: Filtering (Smoothing and Noise Reduction)\n- **Purpose**: Apply blur filters to reduce noise and smooth images\n- **Kernel Size Parameter**: Slider (1-21, odd numbers only, default: 5)\n- **Operations**:\n  1. **Gaussian Blur**: Uses Gaussian distribution for smooth blurring\n  2. **Median Blur**: Effective for salt-and-pepper noise (requires kernel size ≥ 3)\n  3. **Average Blur**: Simple box filter averaging\n- **Note**: Kernel size must be odd for proper operation",
    "gaussian": "### Page 2: Filtering (Smoothing and Noise Reduction)\n- **Purpose**: Apply blur filters to reduce noise and smooth images\n- **Kernel Size Parameter**: Slider (1-21, odd numbers only, default: 5)\n- **Operations**:\n  1. **Gaussian Blur**: Uses Gaussian distribution for smooth blurring\n  2. **Median Blur**: Effective for salt-and-pepper noise (requires kernel size ≥ 3)\n  3. **Average Blur**: Simple box filter averaging\n- **Note**: Kernel size must be odd for proper operation",
    "median": "### Page 2: Filtering (Smoothing and Noise Reduction)\n- **Purpose**: Apply blur filters to reduce noise and smooth images\n- **Kernel Size Parameter**: Slider (1-21, odd numbers only, default: 5)\n- **Operations**:\n  1. **Gaussian Blur**: Uses Gaussian distribution for smooth blurring\n  2. **Median Blur**: Effective for salt-and-pepper noise (requires kernel size ≥ 3)\n  3. **Average Blur**: Simple box filter averaging\n- **Note**: Kernel size must be odd for proper operation",
    "smooth": "### Page 2: Filtering (Smoothing and Noise Reduction)\n- **Purpose**: Apply blur filters to reduce noise and smooth images\n- **Kernel Size Parameter**: Slider (1-21, odd numbers only, default: 5)\n- **Operations**:\n  1. **Gaussian Blur**: Uses Gaussian distribution for smooth blurring\n  2. **Median Blur**: Effective for salt-and-pepper noise (requires kernel size ≥ 3)\n  3. **Average Blur**: Simple box filter averaging\n- **Note**: Kernel size must be odd for proper operation",
    "noise": "### Page 2: Filtering (Smoothing and Noise Reduction)\n- **Purpose**: Apply blur filters to reduce noise and smooth images\n- **Kernel Size Parameter**: Slider (1-21, odd numbers only, default: 5)\n- **Operations**:\n  1. **Gaussian Blur**: Uses Gaussian distribution for smooth blurring\n  2. **Median Blur**: Effective for salt-and-pepper noise (requires kernel size ≥ 3)\n  3. **Average Blur**: Simple box filter averaging\n- **Note**: Kernel size must be odd for proper operation",
    
    "edge": "### Page 3: Edge Detection\n- **Purpose**: Detect edges and boundaries in images\n- **Canny Parameters**:\n  - Threshold1: Slider (0-255, default: 100)\n  - Threshold2: Slider (0-255, default: 200)\n- **Operations**:\n  1. **Sobel**: Detects edges using gradient in X and Y directions\n  2. **Laplacian**: Second-order derivative edge detection\n  3. **Canny**: Advanced edge detector with two thresholds for better control\n- **Note**: Sobel and Laplacian have no parameters; Canny uses the threshold sliders",
    "sobel": "### Page 3: Edge Detection\n- **Purpose**: Detect edges and boundaries in images\n- **Canny Parameters**:\n  - Threshold1: Slider (0-255, default: 100)\n  - Threshold2: Slider (0-255, default: 200)\n- **Operations**:\n  1. **Sobel**: Detects edges using gradient in X and Y directions\n  2. **Laplacian**: Second-order derivative edge detection\n  3. **Canny**: Advanced edge detector with two thresholds for better control\n- **Note**: Sobel and Laplacian have no parameters; Canny uses the threshold sliders",
    "laplacian": "### Page 3: Edge Detection\n- **Purpose**: Detect edges and boundaries in images\n- **Canny Parameters**:\n  - Threshold1: Slider (0-255, default: 100)\n  - Threshold2: Slider (0-255, default: 200)\n- **Operations**:\n  1. **Sobel**: Detects edges using gradient in X and Y directions\n  2. **Laplacian**: Second-order derivative edge detection\n  3. **Canny**: Advanced edge detector with two thresholds for better control\n- **Note**: Sobel and Laplacian have no parameters; Canny uses the threshold sliders",
    "canny": "### Page 3: Edge Detection\n- **Purpose**: Detect edges and boundaries in images\n- **Canny Parameters**:\n  - Threshold1: Slider (0-255, default: 100)\n  - Threshold2: Slider (0-255, default: 200)\n- **Operations**:\n  1. **Sobel**: Detects edges using gradient in X and Y directions\n  2. **Laplacian**: Second-order derivative edge detection\n  3. **Canny**: Advanced edge detector with two thresholds for better control\n- **Note**: Sobel and Laplacian have no parameters; Canny uses the threshold sliders",
    
    "threshold": "### Page 4: Thresholding\n- **Purpose**: Convert images to binary (black/white) based on intensity thresholds\n- **Global Threshold Parameter**: Slider (0-255, default: 127)\n- **Adaptive Threshold Parameters**:\n  - Block Size: Slider (3-51, odd numbers, default: 11)\n  - C Value: Slider (-20 to 20, default: 2) - subtracted from mean\n- **Operations**:\n  1. **Global Threshold**: Single threshold value for entire image\n  2. **Adaptive Mean**: Calculates threshold locally using mean of neighborhood\n  3. **Adaptive Gaussian**: Calculates threshold locally using Gaussian-weighted sum\n- **Use Cases**: Global works well for uniform lighting; Adaptive works better for varying illumination",
    "binary": "### Page 4: Thresholding\n- **Purpose**: Convert images to binary (black/white) based on intensity thresholds\n- **Global Threshold Parameter**: Slider (0-255, default: 127)\n- **Adaptive Threshold Parameters**:\n  - Block Size: Slider (3-51, odd numbers, default: 11)\n  - C Value: Slider (-20 to 20, default: 2) - subtracted from mean\n- **Operations**:\n  1. **Global Threshold**: Single threshold value for entire image\n  2. **Adaptive Mean**: Calculates threshold locally using mean of neighborhood\n  3. **Adaptive Gaussian**: Calculates threshold locally using Gaussian-weighted sum\n- **Use Cases**: Global works well for uniform lighting; Adaptive works better for varying illumination",
    "adaptive": "### Page 4: Thresholding\n- **Purpose**: Convert images to binary (black/white) based on intensity thresholds\n- **Global Threshold Parameter**: Slider (0-255, default: 127)\n- **Adaptive Threshold Parameters**:\n  - Block Size: Slider (3-51, odd numbers, default: 11)\n  - C Value: Slider (-20 to 20, default: 2) - subtracted from mean\n- **Operations**:\n  1. **Global Threshold**: Single threshold value for entire image\n  2. **Adaptive Mean**: Calculates threshold locally using mean of neighborhood\n  3. **Adaptive Gaussian**: Calculates threshold locally using Gaussian-weighted sum\n- **Use Cases**: Global works well for uniform lighting; Adaptive works better for varying illumination",
    
    "morphology": "### Page 5: Morphological Operations\n- **Purpose**: Shape-based image processing operations\n- **Parameters**:\n  - Kernel Size: Slider (1-21, odd numbers, default: 3)\n  - Iterations: Slider (1-5, default: 1)\n- **Operations**:\n  1. **Erosion**: Shrinks objects, removes small noise\n  2. **Dilation**: Expands objects, fills holes\n  3. **Opening**: Erosion followed by dilation (removes noise, preserves shape)\n  4. **Closing**: Dilation followed by erosion (fills gaps, preserves shape)\n- **Use Cases**: Useful for binary images, noise removal, shape analysis",
    "erosion": "### Page 5: Morphological Operations\n- **Purpose**: Shape-based image processing operations\n- **Parameters**:\n  - Kernel Size: Slider (1-21, odd numbers, default: 3)\n  - Iterations: Slider (1-5, default: 1)\n- **Operations**:\n  1. **Erosion**: Shrinks objects, removes small noise\n  2. **Dilation**: Expands objects, fills holes\n  3. **Opening**: Erosion followed by dilation (removes noise, preserves shape)\n  4. **Closing**: Dilation followed by erosion (fills gaps, preserves shape)\n- **Use Cases**: Useful for binary images, noise removal, shape analysis",
    "dilation": "### Page 5: Morphological Operations\n- **Purpose**: Shape-based image processing operations\n- **Parameters**:\n  - Kernel Size: Slider (1-21, odd numbers, default: 3)\n  - Iterations: Slider (1-5, default: 1)\n- **Operations**:\n  1. **Erosion**: Shrinks objects, removes small noise\n  2. **Dilation**: Expands objects, fills holes\n  3. **Opening**: Erosion followed by dilation (removes noise, preserves shape)\n  4. **Closing**: Dilation followed by erosion (fills gaps, preserves shape)\n- **Use Cases**: Useful for binary images, noise removal, shape analysis",
    "opening": "### Page 5: Morphological Operations\n- **Purpose**: Shape-based image processing operations\n- **Parameters**:\n  - Kernel Size: Slider (1-21, odd numbers, default: 3)\n  - Iterations: Slider (1-5, default: 1)\n- **Operations**:\n  1. **Erosion**: Shrinks objects, removes small noise\n  2. **Dilation**: Expands objects, fills holes\n  3. **Opening**: Erosion followed by dilation (removes noise, preserves shape)\n  4. **Closing**: Dilation followed by erosion (fills gaps, preserves shape)\n- **Use Cases**: Useful for binary images, noise removal, shape analysis",
    "closing": "### Page 5: Morphological Operations\n- **Purpose**: Shape-based image processing operations\n- **Parameters**:\n  - Kernel Size: Slider (1-21, odd numbers, default: 3)\n  - Iterations: Slider (1-5, default: 1)\n- **Operations**:\n  1. **Erosion**: Shrinks objects, removes small noise\n  2. **Dilation**: Expands objects, fills holes\n  3. **Opening**: Erosion followed by dilation (removes noise, preserves shape)\n  4. **Closing**: Dilation followed by erosion (fills gaps, preserves shape)\n- **Use Cases**: Useful for binary images, noise removal, shape analysis",
    
    "enhancement": "### Page 6: Image Enhancement\n- **Purpose**: Improve image quality and contrast\n- **Operations**:\n  1. **Histogram Equalization**: Improves global contrast by redistributing pixel intensities (applied in YCrCb color space)\n  2. **Show Histogram**: Displays RGB channel histograms for analysis\n  3. **Sharpening**: Enhances edges using a 3x3 sharpening kernel\n- **No parameters required** - direct operations",
    "enhance": "### Page 6: Image Enhancement\n- **Purpose**: Improve image quality and contrast\n- **Operations**:\n  1. **Histogram Equalization**: Improves global contrast by redistributing pixel intensities (applied in YCrCb color space)\n  2. **Show Histogram**: Displays RGB channel histograms for analysis\n  3. **Sharpening**: Enhances edges using a 3x3 sharpening kernel\n- **No parameters required** - direct operations",
    "histogram": "### Page 6: Image Enhancement\n- **Purpose**: Improve image quality and contrast\n- **Operations**:\n  1. **Histogram Equalization**: Improves global contrast by redistributing pixel intensities (applied in YCrCb color space)\n  2. **Show Histogram**: Displays RGB channel histograms for analysis\n  3. **Sharpening**: Enhances edges using a 3x3 sharpening kernel\n- **No parameters required** - direct operations",
    "sharpen": "### Page 6: Image Enhancement\n- **Purpose**: Improve image quality and contrast\n- **Operations**:\n  1. **Histogram Equalization**: Improves global contrast by redistributing pixel intensities (applied in YCrCb color space)\n  2. **Show Histogram**: Displays RGB channel histograms for analysis\n  3. **Sharpening**: Enhances edges using a 3x3 sharpening kernel\n- **No parameters required** - direct operations",
    "contrast": "### Page 6: Image Enhancement\n- **Purpose**: Improve image quality and contrast\n- **Operations**:\n  1. **Histogram Equalization**: Improves global contrast by redistributing pixel intensities (applied in YCrCb color space)\n  2. **Show Histogram**: Displays RGB channel histograms for analysis\n  3. **Sharpening**: Enhances edges using a 3x3 sharpening kernel\n- **No parameters required** - direct operations",
    
    "batch": "### Page 7: Batch Processing\n- **Purpose**: Apply same operation to multiple images simultaneously\n- **Features**:\n  - Upload multiple images at once\n  - Select operation: \"Grayscale\" or \"Gaussian Blur (k=5)\"\n  - View before/after for each image\n- **Note**: This page operates independently and doesn't use the global state",
    "multiple": "### Page 7: Batch Processing\n- **Purpose**: Apply same operation to multiple images simultaneously\n- **Features**:\n  - Upload multiple images at once\n  - Select operation: \"Grayscale\" or \"Gaussian Blur (k=5)\"\n  - View before/after for each image\n- **Note**: This page operates independently and doesn't use the global state",
    
    "face": "### Page 8: Real-Time Face Detection\n- **Purpose**: Detect faces, eyes, and smiles using webcam\n- **Features**:\n  - Uses Haar Cascade classifiers (frontal face, eyes, smile)\n  - Real-time video processing from webcam\n  - Applies Gaussian blur for preprocessing\n  - Draws bounding boxes: Green for faces, Blue for eyes, Red for smiles\n- **Requirements**: Webcam access required",
    "detection": "### Page 8: Real-Time Face Detection\n- **Purpose**: Detect faces, eyes, and smiles using webcam\n- **Features**:\n  - Uses Haar Cascade classifiers (frontal face, eyes, smile)\n  - Real-time video processing from webcam\n  - Applies Gaussian blur for preprocessing\n  - Draws bounding boxes: Green for faces, Blue for eyes, Red for smiles\n- **Requirements**: Webcam access required",
    "webcam": "### Page 8: Real-Time Face Detection\n- **Purpose**: Detect faces, eyes, and smiles using webcam\n- **Features**:\n  - Uses Haar Cascade classifiers (frontal face, eyes, smile)\n  - Real-time video processing from webcam\n  - Applies Gaussian blur for preprocessing\n  - Draws bounding boxes: Green for faces, Blue for eyes, Red for smiles\n- **Requirements**: Webcam access required",
}


SYSTEM_PROMPT = """You are an expert assistant for a Digital Image Processing (DIP) web application built with Streamlit, OpenCV, and NumPy. Your role is to guide users through all available features and help them achieve their image processing goals.

## PROJECT OVERVIEW
This is a comprehensive image processing web application with 9 main pages accessible through the Streamlit sidebar. Users upload images on the Home page, then navigate to specific processing pages to apply various operations. The application maintains state between pages, allowing users to chain multiple operations.

## AVAILABLE PAGES (Summary)
- **Home Page**: Upload images (PNG, JPG, JPEG, WEBP), view comparison, reset, download
- **Page 1**: Basic Operations (Grayscale, Invert)
- **Page 2**: Filtering (Gaussian, Median, Average blur)
- **Page 3**: Edge Detection (Sobel, Laplacian, Canny)
- **Page 4**: Thresholding (Global, Adaptive Mean, Adaptive Gaussian)
- **Page 5**: Morphological Operations (Erosion, Dilation, Opening, Closing)
- **Page 6**: Image Enhancement (Histogram Equalization, Histogram, Sharpening)
- **Page 7**: Batch Processing (Multiple images)
- **Page 8**: Real-Time Face Detection (Webcam)
- **Page 9**: Assistant (This chat interface)

## TECHNICAL DETAILS
- Images are processed as NumPy arrays in RGB format
- Original image stored globally, processed image updated after each operation
- Operations are chainable: each page uses the latest processed image as input
- Users must upload an image on Home page first

## YOUR RESPONSIBILITIES
1. Guide users to the correct page for their task
2. Explain parameters and suggest values when detailed information is provided
3. Recommend workflows and operation sequences
4. Troubleshoot issues
5. Provide educational explanations when asked
6. Give practical tips and best practices

Always be helpful, clear, and guide users step-by-step. When detailed information about specific features is provided in the context, use it to give comprehensive answers."""
